name: OrangeFox - Build A31 - Custom Fork

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Free space
        run: |
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc /opt/hostedtoolcache
          df -h

      - name: Install deps & NEW repo
        run: |
          sudo apt update
          sudo apt install -y git-core gnupg flex bison build-essential zip curl zlib1g-dev gcc-multilib g++-multilib libc6-dev-i386 lib32ncurses-dev lib32z1-dev x11proto-core-dev libx11-dev libgl1-mesa-dev libxml2-utils xsltproc unzip python3 python3-pip schedtool lz4
          git config --global user.name "runner"
          git config --global user.email "runner@github.com"
          # Eski repo'yu sil, yenisini kur
          sudo rm -f /usr/bin/repo
          mkdir -p ~/.bin
          curl https://storage.googleapis.com/git-repo-downloads/repo > ~/.bin/repo
          chmod a+x ~/.bin/repo
          echo 'export PATH=~/.bin:$PATH' >> ~/.bashrc
          echo 'export PATH=~/.bin:$PATH' >> $GITHUB_PATH
          ~/.bin/repo --version

      - name: Sync Fox 12.1
        run: |
          export PATH=~/.bin:$PATH
          mkdir -p ~/fox_12.1
          cd ~/fox_12.1
          repo init -u https://github.com/OrangeFoxRecovery/OrangeFox-Manifests.git -b fox_12.1 --depth=1
          repo sync -c -j$(nproc --all) --force-sync --no-clone-bundle --no-tags
          echo "SYNC OK"
          ls -lh

      - name: Clone YOUR A31 tree
        run: |
          cd ~/fox_12.1
          rm -rf device/samsung/a31
          git clone https://github.com/KernelMasterX/orangefox-for-galaxy-a31.git device/samsung/a31
          echo "TW_SCREEN_BLANK_ON_BOOT := true" >> device/samsung/a31/BoardConfig.mk
          ls device/samsung/a31/

      - name: Build
        run: |
          export PATH=~/.bin:$PATH
          cd ~/fox_12.1
          export ALLOW_MISSING_DEPENDENCIES=true
          export FOX_BUILD_DEVICE=a31
          export LC_ALL=C
          source build/envsetup.sh
          lunch twrp_a31-eng
          mka recoveryimage -j$(nproc --all)

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: OrangeFox-A31-Custom
          path: |
            ~/fox_12.1/out/target/product/a31/OrangeFox*.zip
            ~/fox_12.1/out/target/product/a31/recovery.img
